sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
linkReplacements:
  - "http://nexus.sonatype.org/oss-repository-hosting.html/scalatest-maven-plugin|https://github.com/scalatest/scalatest-maven-plugin"