language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: C5CwP6kvqhtT8BZIGfWDl94KdZGP2X4kU4WIkwmVJVEn6zQ+Mo3nKohmAbB0KDQxg2OEgzEzNt+HXfygldLLReXd7JSV5oDBXmHNO57QiH7TQU1OG6ydf/609l6p+yDj+D+fwQO33VISsw0Ijpp2mF4naS8tr9Y9OWfZ62ALzQtljaNbeI1oOOo8u6qQd3Xyw0DyAJZ3miaqcu02aGyPBivLOSgh3Blmy1kpBA4sVsIL/oz0iRLNPNE3VChmTtgce8ACR8vjJd1Fzm8G4zjUcAm+hg75fEw785RfN2WvIcKhQ2pnLp/rzF+YvLz7xonZjQ1aHbpLrAMX+rnznO1yBQlhfxu82wfZPFIhEmqEO1bW23TMlsvDocdqZIofvENeE9qDbVpiOHU0T1cr4akrgw7okkBzFRz1kPS6gNMDb5Y/ByTrBtmfbnxLuRqa8VZkCrdvMgxZwT6d93aNMP9Q8zUPpW2TxYOaowZb3gr8kBO0AiDVPpT9tR4yEillFWpLuHVcTNXR1Hons8JtPFqiyfH+Ye38pw7YkaHtKdDN7lVxf5DP9I0L7mAvbPWKIHfIoshIwBugQEKBGQ6EVawqL+0dZVDDlzg0SK7Be5KqVBvvkdjACtT5nu+WA8PcegU3pr1U2Vqt/Y161yZA10Z5HGawpsSV4srxLsAyW0Up/ZE=

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"
