language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"